# Generated by Django 5.2.7 on 2025-11-29 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityinvitation_communityjoinrequest_and_more'),
        ('post', '0002_follow_notification_postview_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.community'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('follow', 'Follow'), ('community_invite', 'Community Invitation'), ('community_join_request', 'Join Request'), ('community_join_approved', 'Join Approved'), ('community_post', 'New Community Post'), ('community_role_changed', 'Role Changed')], max_length=50),
        ),
    ]
