# Generated by Django 5.2.7 on 2025-11-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityinvitation_communityjoinrequest_and_more'),
        ('post', '0003_notification_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, help_text='If set, this is a community post. If null, it is a personal post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.community'),
        ),
    ]
