# Generated by Django 5.2.7 on 2025-11-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned posts appear at the top'),
        ),
    ]
