# Generated by Django 4.2.27 on 2026-01-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0004_delete_userinterest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_post_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Categories/subcategories this post belongs to', related_name='posts', to='interest.subcategory'),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence'), ('misinformation', 'Misinformation'), ('copyright', 'Copyright Violation'), ('inappropriate_content', 'Inappropriate Content'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the report', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='post.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_posts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='post_postre_post_id_2d7f43_idx'), models.Index(fields=['reporter', '-created_at'], name='post_postre_reporte_0e7381_idx'), models.Index(fields=['status', '-created_at'], name='post_postre_status_cd1240_idx')],
                'unique_together': {('reporter', 'post')},
            },
        ),
    ]
