# Generated by Django 4.2.27 on 2026-01-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_subcategories_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_from',
            field=models.ForeignKey(blank=True, help_text='If set, this post is a share of another post. Points to the original post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to='post.post'),
        ),
    ]
