# Generated by Django 5.2.7 on 2025-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_category_remove_interestsubcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterest',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User Interest', 'verbose_name_plural': 'User Interests'},
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
