# Generated by Django 5.2.7 on 2025-11-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_alter_userinterest_options_remove_userinterest_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
