# Generated by Django 4.2.27 on 2026-01-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_payment_subscriptionplan_usersubscription_postcredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Mark this plan as recommended'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text="Unique identifier for the plan (e.g., 'premium', 'starter')", max_length=50, unique=True),
        ),
    ]
