# Generated by Django 5.2.7 on 2025-11-29 09:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Why do you want to join?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-members_count', '-created_at'], 'verbose_name_plural': 'Communities'},
        ),
        migrations.RemoveIndex(
            model_name='community',
            name='community_c_members_c153f6_idx',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='community',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(default=1, help_text='Display name for the community', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(help_text='Unique single-word identifier (no spaces).', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', 'Name must be a single word (letters, numbers, _ or -)'), django.core.validators.MinLengthValidator(4, 'Name must be at least 4 characters long')]),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-members_count'], name='community_c_members_f2664d_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-created_at'], name='community_c_created_901a44_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['community', '-joined_at'], name='community_c_communi_fa35d3_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['user', '-joined_at'], name='community_c_user_id_935e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['community', 'is_approved'], name='community_c_communi_ddd09f_idx'),
        ),
        migrations.AddField(
            model_name='communityinvitation',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='community.community'),
        ),
        migrations.AddField(
            model_name='communityinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_community_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_community_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityjoinrequest',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='community.community'),
        ),
        migrations.AddField(
            model_name='communityjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityrule',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='community.community'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['invitee', 'status', '-created_at'], name='community_c_invitee_ff6420_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['community', 'status'], name='community_c_communi_b5c252_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communityinvitation',
            unique_together={('community', 'invitee')},
        ),
        migrations.AddIndex(
            model_name='communityjoinrequest',
            index=models.Index(fields=['community', 'status', '-created_at'], name='community_c_communi_b8315d_idx'),
        ),
        migrations.AddIndex(
            model_name='communityjoinrequest',
            index=models.Index(fields=['user', 'status'], name='community_c_user_id_1ba4e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communityjoinrequest',
            unique_together={('user', 'community')},
        ),
        migrations.AddIndex(
            model_name='communityrule',
            index=models.Index(fields=['community', 'order'], name='community_c_communi_9966ee_idx'),
        ),
    ]
