# Generated by Django 4.2.27 on 2025-12-23 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_alter_room_options_message_is_read_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
